version: "3"

services:
    portainer:
        image: 'docker.io/portainer/portainer-ce:latest'
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        ports:
            - "8000:8000"
            - "9000:9000"
            - "9443:9443"
volumes:
    portainer_data: {}
